title: Hernan Revale # your name (or website title) here
logo: "/images/foto2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science | Economics | Business
  <br><br>
  <p>Consulting | Management | Research</strong></p>
  <br><br>
  <a href="https://www.linkedin.com/in/hernan-revale/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
